import { Container, Flex } from "@mantine/core";
import { Metadata } from "next";
import { HeaderSection } from "../components/HomePage/HeaderSection";

export const metadata: Metadata = {
  title: "Home - Deyse & Matheus",
  description: "Generated by create next app",
};

export default function Home() {
  const pageSections = [() => <HeaderSection />];

  return (
    <Container fluid p={0}>
      {pageSections.map((PageSection, index) => {
        return <PageSection key={index} />;
      })}
    </Container>
  );
}
